name:                mud-hs
version:             0.1.0.0
github:              "githubuser/mud-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mud-hs#readme>

dependencies:
- base >= 4.7 && < 5
- text
- yaml
- MonadRandom
- websockets
- network
- time
- cereal
- containers
- aeson
- unordered-containers
- hashable
- cereal-text 
- lens
- relude
- directory
- filepath
- hslua-core
- hslua-marshalling
- hslua-objectorientation
- hslua-packaging
- hslua-classes
- lua
- mtl
- bytestring
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  mud-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mud-hs

tests:
  mud-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mud-hs
